FROM ubuntu:18.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-8-jdk \
    curl \
    vim \
    net-tools \
    && apt-get clean \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo "Asia/Shanghai" > /etc/timezone
